import src.expression.strategys.OperatorStrategy as strategy

ADDITION_OPERATOR = "+"
SUBTRACTION_OPERATOR = "-"
DIVISION_OPERATOR = "/"
MULTIPLICATION_OPERATOR = "*"
EXPONENTIATION_OPERATOR = "^"

OPERATORS = {
    ADDITION_OPERATOR : strategy.AdditionStrategy(),
    SUBTRACTION_OPERATOR : strategy.SubtractionStrategy(),
    DIVISION_OPERATOR : strategy.DivisionStrategy(),
    MULTIPLICATION_OPERATOR : strategy.MultiplicationStrategy(),
    EXPONENTIATION_OPERATOR : strategy.ExponentiationStrategy(),
}

# greater value is greater priority
OPERATORS_PRIORITY = {
    ADDITION_OPERATOR : 0,
    SUBTRACTION_OPERATOR : 0,
    DIVISION_OPERATOR : 1,
    MULTIPLICATION_OPERATOR : 1,
    EXPONENTIATION_OPERATOR : 2,
}

LOWEST_PRIORITY_OPERATORS = [ADDITION_OPERATOR, SUBTRACTION_OPERATOR]
HIGHEST_PRIORITY_OPERATORS = [MULTIPLICATION_OPERATOR, DIVISION_OPERATOR]
GOD_PRIORITY_OPERATORS = [EXPONENTIATION_OPERATOR]